version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy:v1.17.0
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8080:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml"
    depends_on:
      - service_a_envoy
      - service_a
      - service_b_envoy
      - service_b
      - service_c_envoy
      - service_c

  service_a_envoy:
    image: envoyproxy/envoy:v1.17.0
    volumes:
      - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8786:8786"
      - "8788:8788"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml"
    depends_on:
      - service_a

  service_a:
    build: service_a/
    ports:
    - "8081:8081"

  service_b_envoy:
    image: envoyproxy/envoy:v1.17.0
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8789:8789"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml"
    depends_on:
      - service_b

  service_b:
    build: service_b/
    ports:
    - "8082:8082"

  service_c_envoy:
    image: envoyproxy/envoy:v1.17.0
    volumes:
      - ./service_c/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8790:8790"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml"
    depends_on:
      - service_c

  service_c:
    build: service_c/
    ports:
    - "8083:8083"  
